*/lib/pwm_searchPFF.c: fix build failure with gcc 14.
As initially identified in [Debian bug #1075213], TFBS fails to build
with gcc 14 since implicit int variables and functions declaration are
now fatal.  This change fixes the following symptoms:

	In file included from pwmsearch.xs:4:
	./lib/pwm_searchPFF.c:303:1: error: return type defaults to ‘int’ [-Wimplicit-int]
	  303 | get_sequence(fp,seq_id,sequence)
	      | ^~~~~~~~~~~~
	./lib/pwm_searchPFF.c:414:1: error: return type defaults to ‘int’ [-Wimplicit-int]
	  414 | best_pull(pargs,pbase,pstrand,pscore)
	      | ^~~~~~~~~

[Debian bug #1075213]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075213

Signed-off-by: Étienne Mollier <emollier@debian.org>